config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailings.urls', namespace='mailings')),
                  path('users/', include('users.urls', namespace='users'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mailings/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from mailings.apps import MailingsConfig
from mailings.views import IndexView, MailingListView, MailingCreateView, MailingUpdateView, MailingDeleteView, \
    MailingDetailView, ClientListView, ClientCreateView, ClientUpdateView, ClientDeleteView, LogsListView, \
    toggle_activity

app_name = MailingsConfig.name

urlpatterns = [
    path('', cache_page(180)(IndexView.as_view()), name='index'),
    path('mailings/', MailingListView.as_view(), name='mailings_list'),
    path('mailings/create/', MailingCreateView.as_view(), name='mailing_create'),
    path('mailings/<int:pk>/detail/', MailingDetailView.as_view(), name='mailing_detail'),
    path('mailings/<int:pk>/update/', MailingUpdateView.as_view(), name='mailing_update'),
    path('mailings/<int:pk>/delete/', MailingDeleteView.as_view(), name='mailing_delete'),
    path('activity/<int:pk>/', toggle_activity, name='toggle_activity'),

    path('mailings/logs/<int:pk>/', LogsListView.as_view(), name='logs_list'),

    path('mailings/clients/', cache_page(180)(ClientListView.as_view()), name='clients_list'),
    path('mailings/clients/create/', ClientCreateView.as_view(), name='client_create'),
    path('mailings/clients/<int:pk>/update/', ClientUpdateView.as_view(), name='client_update'),
    path('mailings/clients/<int:pk>/delete/', ClientDeleteView.as_view(), name='client_delete'),
]

users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path


from users.apps import UsersConfig
from users.views import RegisterView, recovery_password, verification, UserUpdateView, UserListView, \
    toggle_activity_user

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('recovery/', recovery_password, name='recovery'),
    path('verify/<verification_key>', verification, name='verify'),
    path('users/list/', UserListView.as_view(), name='users_list'),
    path('users/toggle_activity_user/<int:pk>', toggle_activity_user, name='toggle_activity_user'),
]

mailings/models.py
from django.conf import settings
from django.db import models
from django.utils.timezone import now

NULLABLE = {
    'blank': True,
    'null': True
}


class Client(models.Model):
    first_name = models.CharField(max_length=150, verbose_name='имя')
    last_name = models.CharField(max_length=150, verbose_name='фамилия')
    email = models.EmailField(unique=True, verbose_name='почта')
    comment = models.TextField(verbose_name='комментарий', **NULLABLE)

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')

    def __str__(self):
        return f'{self.email} ({self.first_name} {self.last_name})'

    class Meta:
        verbose_name = 'клиент'
        verbose_name_plural = 'клиенты'


class Mailing(models.Model):
    PERIOD_DAILY = 'Ежедневно'
    PERIOD_WEEKLY = 'Раз в неделю'
    PERIOD_MONTHLY = 'Раз в месяц'

    PERIODS = (
        (PERIOD_DAILY, 'Ежедневно'),
        (PERIOD_WEEKLY, 'Раз в неделю'),
        (PERIOD_MONTHLY, 'Раз в месяц'),
    )

    STATUS_CREATED = 'Создана'
    STATUS_STARTED = 'Запущена'
    STATUS_DONE = 'Завершена'

    STATUSES = (
        (STATUS_CREATED, 'Создана'),
        (STATUS_STARTED, 'Запущена'),
        (STATUS_DONE, 'Завершена'),
    )

    message_subject = models.CharField(max_length=300, verbose_name='тема сообщения')
    message_boby = models.TextField(verbose_name='тело сообщения', **NULLABLE)

    mailing_time = models.TimeField(default='10:00', verbose_name='время рассылки')
    period = models.CharField(max_length=40, choices=PERIODS, verbose_name='периодичность рассылки')
    status = models.CharField(max_length=40, choices=STATUSES, default=STATUS_CREATED,
                              verbose_name='статус рассылки')
    date_start = models.DateField(default=now, verbose_name='начало рассылки')
    date_end = models.DateField(verbose_name='завершение рассылки', **NULLABLE)

    clients = models.ManyToManyField(Client, verbose_name='клиенты')

    owner = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, **NULLABLE, verbose_name='владелец')

    def __str__(self):
        return self.message_subject

    class Meta:
        verbose_name = 'рассылка'
        verbose_name_plural = 'рассылки'


class MailingLog(models.Model):
    date_last_attempt = models.DateTimeField(verbose_name='дата и время последней попытки')
    status = models.BooleanField(max_length=20, verbose_name='статус попытки')

    mailing = models.ForeignKey(Mailing, on_delete=models.CASCADE, verbose_name='рассылка')
    error = models.TextField(verbose_name='сообщение об ошибке', **NULLABLE)

    def __str__(self):
        return str(self.pk)

    class Meta:
        verbose_name = 'Лог'
        verbose_name_plural = 'Логи'

mailings/forms.py
from django import forms
from django.forms import BaseModelFormSet

from mailings.models import Mailing, Client
from mailings.services import get_active_user

from users.models import User


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class MailingForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Mailing
        # fields = '__all__'  # все поля
        # fields = ('first_name', 'last_name', 'avatar', 'email',)  # либо по полям
        exclude = ('status', 'owner',)  # исключение

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['clients'].queryset = Client.objects.filter(owner=get_active_user())
        # print(self.fields['clients'].queryset)


class ClientForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Client
        # fields = '__all__'  # все поля
        # fields = ('first_name', 'last_name', 'avatar', 'email',)  # либо по полям
        # exclude = ('status',) # исключение
        exclude = ('owner',)

mailings/views.py
import random

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic import TemplateView, ListView, CreateView, UpdateView, DeleteView, DetailView

from blogs.models import Blog
from mailings.forms import MailingForm, ClientForm
from mailings.models import Mailing, Client, MailingLog
from mailings.services import create_task_mailing, delete_task_mailing, set_active_user, get_caches_object
from users.models import User


class IndexView(TemplateView):
    template_name = 'mailings/index.html'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        context_data['title'] = 'Сервис управления рассылками'

        mailings_total = Mailing.objects.all()
        mailings_active = Mailing.objects.exclude(status='Завершена')
        clients = Client.objects.all()
        uniq_clients = set(clients)

        blogs = Blog.objects.all()
        pk_blogs = [i.pk for i in blogs]
        random.shuffle(pk_blogs)
        blogs = [Blog.objects.get(pk=i) for i in pk_blogs[:3]]

        print(blogs)

        context_data['mailings_total'] = len(mailings_total)
        context_data['mailings_active'] = len(mailings_active)
        context_data['uniq_clients'] = len(uniq_clients)
        context_data['blogs_list'] = blogs

        return context_data


class MailingListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Mailing
    permission_required = 'mailings.view_mailing'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)

        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)

        return queryset

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        set_active_user(self.request.user)

        context_data['title'] = 'Все рассылки'
        return context_data


class LogsListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = MailingLog
    permission_required = 'mailings.view_mailinglog'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        queryset = queryset.filter(
            mailing_id=self.kwargs.get('pk')
        )

        return queryset

    def get_context_data(self, *args, **kwargs):
        context_data = super().get_context_data(*args, **kwargs)

        mailing = Mailing.objects.get(pk=self.kwargs.get('pk'))
        log_status = 'Успешно' if mailing.status else 'Не успешно'
        clients = ', '.join([str(i) for i in mailing.clients.all()])

        context_data['title'] = f'Логи рассылки - {mailing}'
        context_data['message'] = mailing.message_boby
        context_data['log_status'] = log_status
        context_data['clients'] = clients

        return context_data


class ClientListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    model = Client
    permission_required = 'mailings.view_client'

    extra_context = {
        'title': 'Все клиенты'
    }

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)

        if not self.request.user.is_staff:
            queryset = queryset.filter(owner=self.request.user)
        return queryset


class MailingCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailings:mailings_list')
    permission_required = 'mailings.add_mailing'

    extra_context = {
        'title': 'Создание рассылки'
    }

    def form_valid(self, form):
        created_object = form.save()
        create_task_mailing(created_object)

        created_object.owner = self.request.user
        created_object.save()
        return super().form_valid(form)


class ClientCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailings:clients_list')
    permission_required = 'mailings.add_client'

    extra_context = {
        'title': 'Создание клиента'
    }

    def form_valid(self, form):
        self.object = form.save()
        self.object.owner = self.request.user
        self.object.save()
        return super().form_valid(form)


class MailingUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Mailing
    form_class = MailingForm
    success_url = reverse_lazy('mailings:mailings_list')
    permission_required = 'mailings.change_mailing'

    extra_context = {
        'title': 'Изменение рассылки'
    }

    def form_valid(self, form):
        changed_object = form.save()

        create_task_mailing(changed_object)
        return super().form_valid(form)


class ClientUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    model = Client
    form_class = ClientForm
    success_url = reverse_lazy('mailings:clients_list')
    permission_required = 'mailings.change_client'

    extra_context = {
        'title': 'Изменение клиента'
    }


class MailingDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Mailing
    success_url = reverse_lazy('mailings:mailings_list')
    permission_required = 'mailings.delete_mailing'

    extra_context = {
        'title': 'Удаление рассылки'
    }

    def form_valid(self, form):
        print(self.object.pk)
        delete_task_mailing(self.object.pk)
        return super().form_valid(form)


class ClientDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    model = Client
    success_url = reverse_lazy('mailings:clients_list')
    permission_required = 'mailings.delete_client'

    extra_context = {
        'title': 'Удаление клиента'
    }


class MailingDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    model = Mailing
    permission_required = 'mailings.view_mailing'

    def get_context_data(self, **kwargs):
        context_data = super().get_context_data(**kwargs)

        context_data['title'] = 'Просмотр рассылки'
        context_data['object'] = get_caches_object(self.object.pk)

        return context_data


@login_required
def toggle_activity(request, pk):
    mailing = Mailing.objects.get(pk=pk)
    if mailing.status != 'Завершена':
        delete_task_mailing(pk)
        mailing.status = 'Завершена'
        mailing.save()
    else:
        create_task_mailing(mailing)
    return redirect(reverse('mailings:mailing_detail', args=[pk]))

mailings/templates/mailings/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>{{ title }}</title>
    <!-- Bootstrap core CSS -->
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <!-- Custom styles for this template -->
    <link href="{% static 'css/album.css' %}" rel="stylesheet">
</head>

<body>

<header>
    <div class="collapse bg-dark" id="navbarHeader">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 col-md-7 py-4">
                    <h4 class="text-white">О сервисе</h4>
                    <p class="text-muted">Сервис позволяет просматривать, создавать, редактировать, а также удалять
                        рассылки, которые отправляются по установленному расписанию </p>
                </div>
                <div class="col-sm-4 offset-md-1 py-4">
                    <h4 class="text-white">Меню</h4>
                    {% if user.is_authenticated %}
                    <span class="text-white"> Вы зашли как:  {{ user }} </span>
                    <br>
                    {% if user.is_staff %}
                    <span class="text-white"> Вы менеджер </span>
                    <hr>
                    {% endif %}
                    {% endif %}
                    <ul class="list-unstyled">
                        <li><a href="{% url 'mailings:index' %}">Главная</a></li>
                        {% if user.is_authenticated %}
                        <li><a href="{% url 'users:profile' %}">Профиль</a></li>
                        {% if user.is_staff %}
                        <li><a href="{% url 'users:users_list' %}">Пользователи</a></li>
                        {% endif %}
                        {% if not user.is_staff %}
                        <li><a href="{% url 'mailings:clients_list' %}">Клиенты</a></li>
                        {% endif %}
                        <li><a href="{% url 'mailings:mailings_list' %}">Рассылки</a></li>
                        <li><a href="{% url 'users:logout' %}">Выйти</a></li>
                        {% else %}
                        <li><a href="{% url 'users:login' %}" {# class="text-white" #}>Войти</a></li>
                        <li><a href="{% url 'users:register' %}" {# class="text-white" #}>Регистрация</a></li>
                        {% endif %}
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="navbar navbar-dark bg-dark box-shadow">
        <div class="container d-flex justify-content-between">
            <a href="{% url 'mailings:index' %}" class="navbar-brand d-flex align-items-center">

                <strong>Mailing service</strong>
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarHeader"
                    aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
        </div>
    </div>
</header>

<main role="main">

    <section class="jumbotron text-center">
        <div class="container">
            <h1 class="jumbotron-heading">{{ title }}</h1>
        </div>
    </section>

    <div class="album py-5 bg-light">
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
    </div>

</main>



<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"
        integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN"
        crossorigin="anonymous"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/holder.min.js' %}"></script>
</body>
</html>

mailings/templates/mailings/client_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}

<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {{ title }}
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить {{ object }}?</p>
                <button type="submit" class="bth btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'mailings:clients_list' %}"> Отмена</a>
            </div>
        </div>
    </div>
</form>

{% endblock %}

mailings/templates/mailings/client_form.html
{% extends 'mailings/base.html' %}

{% block content %}
<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование
                {% else %}
                Добавление клиента
                {% endif %}

            </div>
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>

            </div>
        </div>
    </div>
</form>


{% endblock %}

mailings/templates/mailings/client_list.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="row">

    <div class="col-12 mb-5">
        <a class="btn btn-primary" href="{% url 'mailings:client_create' %}">Добавить клиента</a>
    </div>

    {% for object in object_list %}
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="card-text">{{ object }}</h4>
            </div>
            <div class="card-body">
                <span class="text">Имя: {{ object.first_name }}</span><br>
                <span class="text">Фамилия: {{ object.last_name }}</span><br>
                <span class="text">email: {{ object.email }}</span><br>
                <span class="text">Комментарий: {{ object.comment }}</span><br>
            </div>
            <div class="card-footer">
                <a href="{% url 'mailings:client_update' object.pk %}" class="btn btn-link">Изменить</a>
                <a href="{% url 'mailings:client_delete' object.pk %}" class="btn btn-outline-danger float-right">Удалить</a>
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

mailings/templates/mailings/index.html
{% extends 'mailings/base.html' %}

{% block content%}

<div>
    <div class="row text-center">
        <h4 class="">Полезная информация:</h4>
    </div>
    <div class="container">
    <div class="row text-center">
        <div class="col-4 lead">Количество рассылок всего: {{ mailings_total }} </div>
        <div class="col-4 lead">Количество активных рассылок: {{ mailings_active }} </div>
        <div class="col-4 lead">Количество уникальных клиентов для рассылок: {{ uniq_clients }} </div>
    </div>
    </div>
</div>
<div class="container">
    <div class="row text-center">
        <h4 class="">Статьи из блога:</h4>
    </div>
    <div class="row text-center">
        {% for blog in blogs_list %}
        <div class="col-4">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="lead"> {{ blog.header }} </h4>
                </div>
                <div class="card-body">
                    <p class="list-unstyled mt-3 mb-4 text-start m-3">
                        {{ blog.body|truncatechars:50 }}
                    </p>
                </div>
            </div>
        </div>
{% endfor %}
    </div>
</div>

{% endblock %}

mailings/templates/mailings/mailing_confirm_delete.html
{% extends 'mailings/base.html' %}

{% block content %}

<form method="post" class="row">
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {{ title }}
            </div>
            <div class="card-body">
                {% csrf_token %}
                <p>Действительно хотите удалить {{ object }}?</p>
                <button type="submit" class="bth btn-outline-danger">
                    Удалить
                </button>
                <a class="btn btn-outline-warning" href="{% url 'mailings:mailings_list' %}"> Отмена</a>
            </div>
        </div>
    </div>
</form>

{% endblock %}

mailings/templates/mailings/mailing_detail.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">{{ object|title }}</h1>
</div>
<div class="row text-center">
    <div class="col-6">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="my-0 font-weight-normal">О рассылке</h4>
            </div>
            <div class="card-body">
                <p class="text">Текст рассылки:<br> {{ object.message_boby }}</p><br>
                <ul class="list-unstyled mt-3 mb-4 text-start m-3">
                    <li class="mb-2">Время рассылки: {{ object.mailing_time }}</li>
                    <li class="mb-2">Периодичность: {{ object.period }}</li>
                    <li class="mb-2">Статус: {{ object.status }}</li>
                    <li class="mb-2">Начало: {{ object.date_start }}</li>
                    <li class="mb-2">Завершение: {{ object.date_end|default:"-" }}</li>
                </ul>
                <table class="table">
                    <tr>
                        <td>Клиенты:</td>
                        <td>
                            {% for client in object.clients.all %}
                            {{ client }}<br>
                            {% endfor %}
                        </td>
                    </tr>
                </table>
                <hr>
                <a href="{% url 'mailings:logs_list' object.pk %}" class="btn btn-lg btn-block btn-outline-primary">Логи
                    рассылки</a>
                <hr>
                {% if object.status == "Завершена" %}
                <a href="{% url 'mailings:toggle_activity' object.pk %}"
                   class="btn btn-lg btn-block btn-outline-primary">Восстановить рассылку</a>
                {% else %}
                <a href="{% url 'mailings:toggle_activity' object.pk %}"
                   class="btn btn-lg btn-block btn-outline-primary">Остановить рассылку</a>
                {% endif %}
            </div>
        </div>
    </div>
</div>

{% endblock %}

mailings/templates/mailings/mailing_form.html
{% extends 'mailings/base.html' %}

{% block content %}

<form method="post" class="row">

    <div class="col-6">
        <div class="card">
            <div class="card-header">
                {% if object %}
                Редактирование
                {% else %}
                Добавление рассылки
                {% endif %}

            </div>
            <div class="card-body">

                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-outline-success">
                    {% if object %}
                    Сохранить
                    {% else %}
                    Добавить
                    {% endif %}
                </button>

            </div>
        </div>
    </div>
</form>


{% endblock %}

mailings/templates/mailings/mailing_list.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="row">
    {% if not user.is_staff %}
    <div class="col-12 mb-5">
        <a class="btn btn-primary" href="{% url 'mailings:mailing_create' %}">Добавить рассылку</a>
    </div>
    {% endif %}

    {% for object in object_list %}
    <div class="col-4">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="card-text">{{ object.message_subject|title }}</h4>
            </div>
            <div class="card-body">
                <p class="text">Текст рассылки:<br> {{ object.message_boby|truncatechars:100 }}</p><br>
                <span class="text">Время рассылки: {{ object.mailing_time }}</span><br>
                <span class="text">Периодичность: {{ object.period }}</span><br>
                <span class="text">Статус: {{ object.status }}</span><br>
                <span class="text">Начало: {{ object.date_start }}</span><br>
                <span class="text">Завершение: {{ object.date_end|default:"-" }}</span><br>
            </div>
            <div class="card-footer">
                <a href="{% url 'mailings:mailing_detail' object.pk %}" class="btn btn-link">Детали</a>
                {% if not user.is_staff %}
                <a href="{% url 'mailings:mailing_update' object.pk %}" class="btn btn-link">Изменить</a>
                <a href="{% url 'mailings:mailing_delete' object.pk %}" class="btn btn-outline-danger float-right">Удалить</a>
                {% endif %}
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}

mailings/templates/mailings/mailinglog_list.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="row">

    {% for object in object_list %}
    <div class="col-8">
        <div class="card mb-4 box-shadow">
            <div class="card-header">
                <h4 class="card-text">{{ object }}</h4>
            </div>
            <div class="card-body">
                <span class="text">Дата и время последней попытки: {{ object.date_last_attempt }}</span><br>
                <span class="text">Статус: {{ log_status }} </span><br>
                <span class="text">Тема сообщения: {{ object.mailing }}</span><br>
                <span class="text">Cообщение: {{ message }}</span><br>
                <span class="text">Клиенты: {{ clients }}</span><br>
                <span class="text">Ошибки: {{ object.error }}</span><br>
            </div>
        </div>
    </div>
    {% endfor %}
</div>


{% endblock %}