config/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
                  path('admin/', admin.site.urls),
                  path('', include('mailings.urls', namespace='mailings')),
                  path('users/', include('users.urls', namespace='users'))
              ] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.contrib.auth.views import LogoutView, LoginView
from django.urls import path


from users.apps import UsersConfig
from users.views import RegisterView, recovery_password, verification, UserUpdateView, UserListView, \
    toggle_activity_user

app_name = UsersConfig.name

urlpatterns = [
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('register/', RegisterView.as_view(), name='register'),
    path('profile/', UserUpdateView.as_view(), name='profile'),
    path('recovery/', recovery_password, name='recovery'),
    path('verify/<verification_key>', verification, name='verify'),
    path('users/list/', UserListView.as_view(), name='users_list'),
    path('users/toggle_activity_user/<int:pk>', toggle_activity_user, name='toggle_activity_user'),
]

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

NULLABLE = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')
    phone = models.CharField(max_length=35, verbose_name='телефон', **NULLABLE)

    verification_key = models.CharField(max_length=25, verbose_name='ключ', **NULLABLE)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        permissions = [
            ('set_active', 'Can block users')
        ]

users/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from users.models import User
from django import forms


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control'


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('email', 'password1', 'password2')


class UserUpdateForm(StyleFormMixin, UserChangeForm):
    class Meta:
        model = User
        fields = ('email', 'password', 'first_name', 'last_name', 'phone')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['password'].widget = forms.HiddenInput()

users/views.py
from random import randint

from django.conf import settings
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import Group
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, UpdateView, ListView

from users.forms import UserRegisterForm, UserUpdateForm
from users.models import User


class RegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    template_name = 'users/register.html'
    success_url = reverse_lazy('users:login')

    def form_valid(self, form):
        new_verification_key = ''.join([str(randint(0, 9)) for _ in range(20)])

        self.object = form.save()
        self.object.verification_key = new_verification_key
        self.object.is_active = False
        self.object.save()
        group = Group.objects.get(name='Пользователь')
        self.object.groups.add(group)

        site = 'http://127.0.0.1:8000'
        url = reverse_lazy('users:verify', kwargs={'verification_key': new_verification_key})

        send_mail(
            subject='Верификация пользователя',
            message=f'Подтвердить адрес почты: {site}{url}',
            from_email=settings.EMAIL_HOST_USER,
            recipient_list=[self.object]
        )

        return super().form_valid(form)


class UserUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    success_url = reverse_lazy('users:profile')
    form_class = UserUpdateForm

    def get_object(self, queryset=None):
        return self.request.user


class UserListView(PermissionRequiredMixin, ListView):
    model = User
    permission_required = 'users.view_user'

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)

        queryset = queryset.exclude(is_staff=True)
        print(queryset)

        return queryset


def verification(request, verification_key):
    try:
        user = User.objects.filter(verification_key=verification_key).first()
        if user:
            user.is_active = True
            user.save()
            return render(request, 'users/confirm_success.html')
        else:
            return render(request, 'users/confirm_failed.html')
    except Exception:
        pass


def recovery_password(request):
    if request.method == 'POST':
        email = request.POST.get('email')
        try:
            user = User.objects.get(email=email)
            new_password = ''.join([str(randint(0, 9)) for _ in range(12)])
            send_mail(
                subject='Восстановление пароля',
                message=f'Ваш новый пароль: {new_password}',
                from_email=settings.EMAIL_HOST_USER,
                recipient_list=[email]
            )
            user.set_password(new_password)
            user.save()
            return redirect(reverse('users:login'))

        except Exception:
            pass

    return render(request, 'users/recovery_password.html')


def toggle_activity_user(request, pk):
    user = get_object_or_404(User, pk=pk)
    if user.is_active:
        user.is_active = False
    else:
        user.is_active = True

    user.save()

    return redirect(reverse('users:users_list'))

users/templates/users/confirm_failed.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="col-12">
    Ошибка подтверждения
</div>

{% endblock %}

users/templates/users/confirm_success.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="col-12">
    Верификация прошла успешно
    <a href="{% url 'users:login' %}" class="btn btn-success">К авторизации</a>
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Вход
                        </h3>
                    </div>
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            Войти
                        </button>
                        <a href="{% url 'users:recovery' %}" class="btn btn-primary">Забыли пароль</a>

                    </div>
                    <div class="card-footer"></div>
                </div>
            </div>

        </div>
    </form>
</div>

{% endblock %}

users/templates/users/recovery_password.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-3">
                {% csrf_token %}
                <input type="email" name="email" placeholder="Введите email" class="form-control mb-5"/>
                <input type="submit" value="Восстановить пароль" class="btn btn-primary">
            </div>
        </div>
    </form>
</div>

{% endblock %}

users/templates/users/register.html
{% extends 'mailings/base.html' %}

{% block content %}
<div class="col-12">
    <form method="post" enctype="multipart/form-data">
        <div class="row">
            <div class="col-3"></div>
            <div class="col-6">
                <div class="card">
                    <div class="card-header">
                        <h3 class="card-title">
                            Регистрация
                        </h3>
                    </div>
                    <div class="card-body">

                        {% csrf_token %}
                        {{ form.as_p }}
                        <button type="submit" class="btn btn-primary">
                            Регистрация
                        </button>

                    </div>
                </div>
            </div>

        </div>
    </form>
</div>
{% endblock %}

users/templates/users/user_form.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="row">
    <div class="col-3">

    </div>
    <div class="col-6">
        <div class="card">
            <div class="card-header">
                Мой профиль
            </div>
            <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-success">Сохранить</button>
                </form>
            </div>

        </div>
    </div>
</div>

{% endblock %}

users/templates/users/user_list.html
{% extends 'mailings/base.html' %}

{% block content %}

<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Зарегистрированные пользователи</h1>
</div>

<div class="container">
    <div class="row text-center">
        {% for object in object_list %}
        <div class="col-3">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Пользователь</h4>
                </div>
                <div class="card-body">
                    <p class="list-unstyled mt-3 mb-4 text-start m-3">Имя:
                        {% if object.first_name %}
                        {{ object.first_name }}
                        {% else %}
                        Не указано
                        {% endif %}
                        <br>Фамилия:
                        {% if object.last_name %}
                        {{ object.last_name }}
                        {% else %}
                        Не указана
                        {% endif %}</p>
                    <p class="list-unstyled mt-3 mb-4 text-start m-3">Почта: {{ object.email }}</p>

                </div>
                <div class="card-footer">
                    {% if object.is_active %}
                <a class="btn btn-warning" href="{% url 'users:toggle_activity_user' object.pk %}">Деактивировать</a>
                {% else %}
                <a class="btn btn-success" href="{% url 'users:toggle_activity_user' object.pk %}">Активировать</a>
                {% endif %}
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}